### ISSUE TITLE
 runtime org.freedesktop.Platform branch 20.08 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/com.inventwithpython.flippy#4]
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

**Comment by takluyver** [comment]
Heads up, if you're posting these messages automatically, it would be useful to include what the current/recommended version is. It appears to be 22.08, according to [this repo](https://gitlab.com/freedesktop-sdk/freedesktop-sdk), but it took me a few minutes to find that.

**Comment by hfiguiere** [comment]
if this was a bot it would be late. 20.08 was deprecated early September of last year.
